name: Android CI
on:
  push:
    branches: [main]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'zulu'
          java-version: '8'
          
      - name: Gradle
        run: ./gradlew build
        
      - name: APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: App
          path: app/build/outputs/apk/debug/app-debug.apk
